### ISSUE TITLE
doubtful shape change in utils.padded_tensor

### ISSUE THREAD

**Issue by seanexplode** [wxl1999/UniCRS#5]
Hi, thanks for sharing the code.

While running the code, I found that in `src/utils.py`, the output shape is modified when `fp16 mixed precision training` is activated.

https://github.com/wxl1999/UniCRS/blob/main/src/utils.py#L44

Due to this, when activating `fp16` training, the code throws error. 
What is the line `t = t // 8 * 8` for?

**Comment by wxl1999** [comment]
Hi, thanks for your attention on this work!


t = t // 8 * 8 aims to change the dimension of the tensor to a multiple of 8, which is suggested for quicker speed.


However, I empirically find that the difference is slight in both speed and performance.


So you can just comment this line.


Hope this can help you!





Xiaolei&nbsp;Wang
***@***.***



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "wxl1999/UniCRS"                                                                                    ***@***.***&gt;;
Date:&nbsp;Wed, Apr 12, 2023 05:18 PM
***@***.***&gt;;
***@***.***&gt;;
Subject:&nbsp;[wxl1999/UniCRS] doubtful shape change in utils.padded_tensor (Issue #5)





 
Hi, thanks for sharing the code.
 
While running the code, I found that in src/utils.py, the output shape is modified when fp16 mixed precision training is activated.
 
https://github.com/wxl1999/UniCRS/blob/main/src/utils.py#L44
 
Due to this, when activating fp16 training, the code throws error, what is the line t = t // 8 * 8 for?

**Comment by seanexplode** [comment]
Thanks for quick reply!
